# -*- coding: utf-8 -*-

UrlToCategoryMap = {
    "http://singpromos.com/beauty/slimming-treatments/": "Beauty & Health",
    "http://singpromos.com/beauty/": "Beauty & Health",
    "http://singpromos.com/fragrances-perfumes/": "Beauty & Health",
    "http://singpromos.com/health/": "Beauty & Health",
    "http://singpromos.com/personal-care/": "Beauty & Health",
    "http://singpromos.com/books/": "Books & Stationery",
    "http://singpromos.com/babies-mothers/": "Children",
    "http://singpromos.com/kids/": "Children",
    "http://singpromos.com/apple/": "Electronics & Gadgets",
    "http://singpromos.com/digital-cameras-dslr/": "Electronics & Gadgets",
    "http://singpromos.com/video-games/": "Electronics & Gadgets",
    "http://singpromos.com/audio-visual/": "Electronics & Gadgets",
    "http://singpromos.com/video-camcorders/": "Electronics & Gadgets",
    "http://singpromos.com/computers-pc/": "Electronics & Gadgets",
    "http://singpromos.com/cosmetics/": "Fashion",
    "http://singpromos.com/fashion-accessories/": "Fashion",
    "http://singpromos.com/footwear/": "Fashion",
    "http://singpromos.com/handbags/": "Fashion",
    "http://singpromos.com/jewellery/": "Fashion",
    "http://singpromos.com/watches/": "Fashion",
    "http://singpromos.com/banks-credit-cards/": "Finance",
    "http://singpromos.com/dining-restaurants-food/": "Food, Dining & Groceries",
    "http://singpromos.com/wine/": "Food, Dining & Groceries",
    "http://singpromos.com/household/": "Home Appliances & Furniture",
    "http://singpromos.com/beds/": "Home Appliances & Furniture",
    "http://singpromos.com/furniture/": "Home Appliances & Furniture",
    "http://singpromos.com/home-appliances/": "Home Appliances & Furniture",
    "http://singpromos.com/kitchenware-cookware/": "Home Appliances & Furniture",
    "http://singpromos.com/places-of-interest/": "Leisure",
    "http://singpromos.com/happenings/": "Malls & Events",
    "http://singpromos.com/warehouse-sales/": "Malls & Events",
    "http://singpromos.com/shopping-malls/": "Malls & Events",
    "http://singpromos.com/department-stores/": "Online & Islandwide",
    "http://singpromos.com/mobile-phones/": "Smartphones",
    "http://singpromos.com/telecoms/": "Smartphones",
    "http://singpromos.com/body-fitness-gym/": "Sports",
    "http://singpromos.com/sports/": "Sports",
    "http://singpromos.com/motor-vehicles/": "Transport(Taxis, Bus)",
    "http://singpromos.com/airlines-flights/": "Vacations",
    "http://singpromos.com/vacations/": "Vacations",
}
